name: Update Deployment Counter

on:
  workflow_run:
    workflows: [Azure Static Web Apps CI/CD]
    branches: [main]
    types:
      - completed

jobs:
  update_counter:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Increment Counter
        id: increment_counter
        run: |
          # Load the current counter value from the file
          counter=$(cat deployment_counter.txt)
          # Increment the counter by 1
          new_counter=$((counter + 1))
          # Update the counter value in the file
          echo "$new_counter" > deployment_counter.txt
          # Store the new counter value as an output
          echo "::set-output name=counter_value::$new_counter"

      - name: Show Updated Counter Value
        env:
          ACTIONSCOUNTER_TOKEN: ${{ secrets.ACTIONSCOUNTER_TOKEN }}
        if: success()
        run: |
          # Get the updated counter value from the previous step's output
          counter_value=${{ steps.increment_counter.outputs.counter_value }}
          echo "Successfully deployed! Current deployment count: $counter_value"
