name: Hugo deploy
on:
  push:
    paths-ignore: counter/deployment_counter.txt
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jakejarvis/hugo-build-action@v0.80.0
      - uses: tibor19/static-website-deploy@v2
        with:
          enabled-static-website: 'true'
          folder: './public'
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
